version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: justlivechat-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: justlivechat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: justlivechat-backend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/justlivechat
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_here}
      - PORT=4000
      - FRONTEND_URL=http://localhost:3000
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: justlivechat-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_EMBED_URL=http://localhost:4000/embed.js
      - NEXT_PUBLIC_API_URL=http://localhost:4000/
      - NODE_ENV=production

volumes:
  postgres_data: 